name: Android CI

permissions:
  contents: write

on:
  push:
    tags:
      - '*'
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build
        env:
          storyteller_f_sign_key: ${{ secrets.SIGNING_KEY }}
          storyteller_f_sign_alias: ${{ secrets.ALIAS }}
          storyteller_f_sign_store_password: ${{ secrets.STORE_PASSWORD }}
          storyteller_f_sign_key_password: ${{ secrets.KEY_PASSWORD }}


      # Example use of `signedReleaseFile` output -- not needed
      - uses: actions/upload-artifact@v4
        with:
          name: Signed app bundle
          path: app/build/outputs/apk/release/*.apk

  release:
    name: Release APK
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v4
        with:
          name: Signed app bundle
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          files: ./*.apk

